### **DATA INGESTATION**

In [8]:
import pandas as pd
import numpy as np

In [9]:
import os

print(os.listdir())

['Experiment.ipynb']

In [10]:
print(os.getcwd())

c:\Users\user\HEALTH PROJECT\Notebook

In [11]:
data_path = r"C:\Users\user\HEALTH PROJECT\Data\Health Data.csv"

data = pd.read_csv(data_path)
data.head()

,patient_id,encounter_timestamp,age,gender,ethnicity,income_level,education_level,employment_status,smoking_status,alcohol_consumption,...,department,length_of_stay,procedures_count,medications_count,complications,readmission_30days,total_treatment_cost,patient_satisfaction_score,discharge_disposition,follow_up_appointment_scheduled
0,P300000,2025-01-01 09:06:00.000000000,69,F,ASIAN,High,Secondary,Employed,current,68 units,...,gen med,2.6,1,5.0,0.0,0,3840.91,8,Home,0
1,P300001,2025-01-01 18:00:05.609198291,53,F,White,Low,College,Retired,yes,6,...,cardiology,6.5,4,9.0,0.0,0,5848.45,7,Home,1
2,P300002,2025-01-01 07:28:11.218396582,57,F,Indian,Upper-Middle,Bachelor,Unemployed,0,4,...,Orthopedics,6.6,1,4.0,1.0,0,8342.71,6,Home,1
3,P300003,2025-01-02 04:23:16.827594873,18,M,White,Upper-Middle,Postgraduate,Employed,0,5,...,ortho,2.9,2,4.0,1.0,0,4263.29,7,Rehab,0
4,P300004,2025-01-02 00:25:22.436793164,69,M,Mixed,Upper-Middle,Secondary,Retired,no,24,...,ONCOLOGY,11.3,2,4.0,0.0,0,6919.41,5,Against Medical Advice,1

In [12]:
data.tail()

,patient_id,encounter_timestamp,age,gender,ethnicity,income_level,education_level,employment_status,smoking_status,alcohol_consumption,...,department,length_of_stay,procedures_count,medications_count,complications,readmission_30days,total_treatment_cost,patient_satisfaction_score,discharge_disposition,follow_up_appointment_scheduled
3995,P900015,2025-10-24 13:55:40.882885148,65,M,black,High,Bachelor,Retired,0,14,...,General Medicine,7.00,3,6.0,0.0,0,4195.97,7,Skilled Nursing,1
3996,P900016,2025-03-01 08:01:23.542096004,47,M,ASIAN,Low,Bachelor,Employed,no,4 units,...,General Medicine,7.34,2,4.0,0.0,0,3588.46,6,Home,1
3997,P900017,2025-08-24 22:12:04.421211360,65,F,CARIBBEAN,Lower-Middle,College,Retired,current,20,...,Cardio,4.60,3,4.0,NaN,0,7039.02,8,Home,1
3998,P900018,2025-01-26 11:04:36.920331741,51,F,White,Low,Primary,Retired,no,32,...,cardiology,5.49,4,5.0,1.0,0,7721.82,6,Home,1
3999,P900019,2025-01-25 13:43:40.828348831,79,F,hispanic,NaN,Secondary,Retired,no,3,...,General Medicine,5.33,1,4.0,NaN,0,4705.29,6,Skilled Nursing,1

In [15]:
print(data.columns)

Index(['patient_id', 'encounter_timestamp', 'age', 'gender', 'ethnicity',
       'income_level', 'education_level', 'employment_status',
       'smoking_status', 'alcohol_consumption', 'physical_activity',
       'sleep_hours', 'diet_score', 'bmi', 'systolic_bp', 'diastolic_bp',
       'heart_rate', 'blood_sugar_fasting', 'cholesterol_total',
       'admission_type', 'department', 'length_of_stay', 'procedures_count',
       'medications_count', 'complications', 'readmission_30days',
       'total_treatment_cost', 'patient_satisfaction_score',
       'discharge_disposition', 'follow_up_appointment_scheduled'],
      dtype='object')